### ISSUE TITLE
README should be updated

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/customer-engagement-bot#1]

**Comment by aprilwebster** [comment]
Had a quick scan through - here are some things that need to be fixed:
- [ ] Update [getting the files](https://github.com/watson-developer-cloud/customer-engagement-bot/blob/master/README.md#getting-the-files) to reference the new repo, not the food-coach repo
- [ ] Points #4 & 5 in [Setting Up the Tone Analyzer Service](https://github.com/watson-developer-cloud/customer-engagement-bot#setting-up-the-tone-analyzer-service) still reference the food coach 
- [ ] [What Does the Customer Engagement App Do](https://github.com/watson-developer-cloud/customer-engagement-bot#what-does-the-customer-engagement-tone-analyzer--conversation-application-do)  
    - This is from food-coach: "After asking you what you ate (if a meal was consumed), the bot asks you how you feel about it. Depending on your emotional tone, the bot provides different feedback."
    - Title of this section? - perhaps 'Customer Engagement Bot Do?' do instead?

**Comment by germanattanasio** [comment]
@aprilwebster can we get someone to work on this? It's just the README

**Comment by germanattanasio** [comment]
fixed in #10
